services:

  redis:
    command: redis-server
    hostname: redis
    image: redis:alpine
    labels:
      NAME: redis

  conferences:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --reload # sleep 9999999999
    env_file:
    - .env
    #    volumes:
    #    - ./src/:/app
    #    - /var/log/opencon:/var/log/opencon
    ports:
    - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started

  
  push_notifications:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    
    command: python workers/push_notifications.py # sleep 99999
    env_file:
    - .env
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started

  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: sfscon
      POSTGRES_USER: sfscon
      POSTGRES_PASSWORD: sfscon
    hostname: postgres
    volumes:
      - /tmp/epaper_pgdata:/var/lib/postgresql/data
