services:

  conferences:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    command: uvicorn main:app --host 0.0.0.0 --reload # sleep 9999999999
    env_file: 
      - .env
    ports:
      - "${SERVER_PORT_CONFERENCES}:8000"
    volumes:
      - opencon-logs:/var/log/opencon
    healthcheck:
      test: curl --fail http://localhost:8000/openapi.json || exit 1
      interval: 300s
      retries: 3
      start_period: 5s
      timeout: 10s
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started

  push_notifications:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    command: mkdir -p python workers/push_notifications.py sleep 10
    env_file: 
      - .env
    ports:
      - "${SERVER_PORT_PUSH_NOTIFICATIONS}:8080"
    volumes:
      - opencon-logs:/var/log/opencon
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started
      conferences:
        condition: service_healthy

  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    hostname: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    command: redis-server
    hostname: redis
    image: redis:alpine
    labels:
      NAME: redis

volumes:
  opencon-logs:
  postgres-data:

