services:

  conferences:
    image: ${DOCKER_IMAGE_CONFERENCES}:${DOCKER_TAG}
    command: uvicorn main:app --host 0.0.0.0 --reload # sleep 9999999999
    env_file: 
      - .env
    ports:
      - "${SERVER_PORT_CONFERENCES}:8000"
    volumes:
      - opencon-logs:/var/log/opencon

  push_notifications:
    image: ${DOCKER_IMAGE_PUSH_NOTIFICATIONS}:${DOCKER_TAG}
    command: python workers/push_notifications.py # sleep 99999
    env_file: 
      - .env
    ports:
      - "${SERVER_PORT_PUSH_NOTIFICATIONS}:8080"
    volumes:
      - opencon-logs:/var/log/opencon

  telegram:
    image: ${DOCKER_IMAGE_TELEGRAM}:${DOCKER_TAG}
    command: python workers/telegram.py # sleep 99999
    env_file: 
      - .env
    ports:
      - "${SERVER_PORT_TELEGRAM}:8080"
    volumes:
      - opencon-logs:/var/log/opencon
  
  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: sfscon
      POSTGRES_USER: sfscon
      POSTGRES_PASSWORD: sfscon
    hostname: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    command: redis-server
    hostname: redis
    image: redis:alpine
    labels:
      NAME: redis

volumes:
  opencon-logs:
  postgres-data:

