services:

  conferences:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    command: uvicorn main:app --host 0.0.0.0 --reload # sleep 9999999999
    env_file: 
      - .env
    ports:
      - "${SERVER_PORT_CONFERENCES}:8000"
    volumes:
      - opencon-logs
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started

  push_notifications:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    command: mkdir -p python workers/push_notifications.py # sleep 99999
    env_file: 
      - .env
    ports:
      - "${SERVER_PORT_PUSH_NOTIFICATIONS}:8080"
    volumes:
      - opencon-logs
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started

  postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_DB: sfscon
      POSTGRES_USER: sfscon
      POSTGRES_PASSWORD: sfscon
    hostname: postgres
    volumes:
      - postgres-data
  
  redis:
    command: redis-server
    hostname: redis
    image: redis:alpine
    labels:
      NAME: redis

volumes:
  opencon-logs:
  postgres-data:

